




/*
     FILE ARCHIVED ON 20:36:28 Jun 1, 2009 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 15:33:41 Jul 30, 2014.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
//<!--Survey is done 08 10 2004-->


function TakeSurvey () {

}


//-->
