




/*
     FILE ARCHIVED ON 16:00:41 Jun 6, 2013 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 15:58:20 Jul 30, 2014.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
//<!--Survey is done 08 10 2004-->


function TakeSurvey () {

}


//-->
